esphome:
  name: bedroom-ac
  platform: ESP8266
  board: esp12e

# Disable logging over UART (required)
logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Bedroom AC Hotspot'
    password: !secret esphome_bedroom_ac_password

captive_portal:

# Main settings
climate:
  - platform: midea
    name: Bedroom AC
    autoconf: true
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    custom_fan_modes:
      - SILENT
      - TURBO

# Beeper Control
switch:
  - platform: template
    name: Bedroom AC Beeper
    icon: mdi:volume-source
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:
